name: "Add an event"
description: Adding events made easy!
labels: [event]

title: "[Event]: "

body:
- type: input
  id: event_date
  attributes:
    label: Date of the event
    description: In the format DD-MM-YYYY
  validations:
    required: true

- type: input
  id: event_title
  attributes:
    label: Title of the event
  validations:
    required: true

- type: input
  id: event_attend
  attributes:
    label: URL to your event
  validations:
    required: true

- type: checkboxes
  id: acknowledge_issue
  attributes:
    label: I acknowledge that the provided information are correct
    options:
      - label: Confirm
        required: true
