name: "Add an event"
description: Adding events made easy!
labels: [event]

title: "[Event]: "

body:
- type: input
  id: date
  attributes:
    label: Date of the event
    description: In the format DD-MM-YYYY
  validations:
    required: true

- type: input
  id: title
  attributes:
    label: Title of the event
  validations:
    required: true

- type: input
  id: attend
  attributes:
    label: URL to your event
  validations:
    required: true
